### ISSUE TITLE
Add dependency SBOM

### ISSUE THREAD

**Issue by joshuatcasey** [paketo-buildpacks/composer#7]
**Given** A developer is using this buildpack to install `composer`
**When** The developer inspects the launch image created by a lifecycle
**Then** The developer should see an SBOM for the dependency downloaded by this buildpack (`composer`)

## Notes:
- Use `paketo-buildpacks/packit/v2` `"sbom".GenerateFromDependency` to ensure that this SBOM has the right information

**Comment by robdimsdale** [comment]
At a minimum, we need to support the legacy SBOM format for backwards compatibility (see e.g. [php-dist](https://github.com/paketo-buildpacks/php-dist/blob/1299723e416fda3575e3ad3e09b63e2ddc5daf2a/build.go#L101)).

Separately, we should also support the new sbom format, which uses the `paketo-buildpacks/packit/v2/sbom.GenerateFromDependency` function. That does not have to be completed as part of the rewrite, though.
